name: Serverest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 Check version Newman and Node
        run: |
              newman --version
              node --version
      
      - name: Step 2 Install Newman-Reporter-Htlmextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      
      - name: Step 3 Execute collection
        run: newman run ./ServeRest_collection.json -g serverest_globals.json -r htmlextra --reporter-html-export ./newman/resultado.html 
      
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
              name: report
              path: ./result/Report.html