name: Signup

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v2.3.1

      - name: Check version of Newman and Node
        run: |
          newman --version
          node --version

      - name: Install Newman Reporter Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Ensure newman directory exists
        run: mkdir -p newman

      - name: Execute Postman collection
        run: newman run ./ServeRest_collection.json -g serverest_globals.json -r htmlextra --reporter-html-export ./newman/resultado.html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: report
          path: ./newman/resultado.html
